name: CI Tests

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    # run every Monday at 4am UTC
    - cron: '0 4 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TOXARGS: '-v'

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.prefix }} ${{ matrix.os }}, ${{ matrix.tox_env }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'py311-test-cov'
            toxposargs: --remote-data=any
            allow_failure: false
            prefix: ''

          - name: MacOS with coverage and remote data
            os: macos-latest
            python: '3.11'
            tox_env: 'py311-test-cov'
            allow_failure: false
            prefix: ''
            toxposargs: --remote-data=any

          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'py311-test'
            allow_failure: false
            prefix: ''

          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'codestyle'
            allow_failure: false
            prefix: ''

          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'pep517'
            allow_failure: false
            prefix: ''

          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'securityaudit'
            allow_failure: false
            prefix: ''

          - os: ubuntu-latest
            python: '3.12'
            tox_env: 'py312-test-devdeps'
            toxposargs: --remote-data=any
            allow_failure: true
            prefix: '(Allowed failure)'

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install HDF5
      if: ${{ contains(matrix.os, 'macos') }}
      run: brew install hdf5
    - name: Install base dependencies
      run: python -m pip install --upgrade pip setuptools tox
    - name: Print Python, pip, setuptools, and tox versions
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -c "import tox; print(f'tox {tox.__version__}')"
    - name: Run tests
      run: tox -e ${{ matrix.tox_env }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.tox_env, '-cov') }}
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
      with:
        files: ./coverage.xml
        verbose: true
